### ISSUE TITLE
nightwatch v1.x

### ISSUE THREAD

**Issue by ysle** [browserstack/browserstack-integration-nodejs#11]
Hi, 
despite haven't seen any update for years, the package works nicely with nightwatch v0.8.
I'm just wondering do we have any chance to support nightwatch v1.x too please?
or if it's given, than just update the examples here accordingly.

the current example throws this with nightwatch ^1.0.19  : 

```sh
> nightwatch-sample@0.1.0 test 
> nightwatch -e android,windows

   An error occurred while trying to start the Nightwatch Runner: Cannot find module 'nightwatch/lib/runner/cli/clirunner.js'
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
       at Function.Module._load (internal/modules/cjs/loader.js:520:25)
       at Module.require (internal/modules/cjs/loader.js:650:17)
       at require (internal/modules/cjs/helpers.js:20:18)
       at Object.<anonymous> (c:\....\nightwatch.conf.js:1:96)
       at Module._compile (internal/modules/cjs/loader.js:702:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
npm ERR! Test failed.  See above for more details.
```
please advise, 
Thanks!

**Comment by agarwalswapnil** [comment]
Hi @ysle 
Thanks for using the package.

I am part of the team here at BrowserStack.
Our team will look into this. In the meantime, would you be open to submitting a pull request for supporting Nightwatch ^1.0.19?
It would be a great help.

If you can do that, we will send you few goodies as a token of gratitude.
Looking forwad to your collaboration.
Thanks.

**Comment by openjck** [comment]
Hm. I'm also running into this, unfortunately. ☹️

**Comment by faboweb** [comment]
+1

**Comment by Varun-garg** [comment]
We are working on this, will get get back in some time.

**Comment by faboweb** [comment]
Awesome! Very much looking forward to this :)

**Comment by openjck** [comment]
@Varun-garg Is this still the recommended tool for running Nightwatch tests in BrowserStack? The BrowserStack support team told me not to use it.

Long story short, there are two pages in the BrowserStack documentation that explain how to run Nightwatch tests:

1. https://www.browserstack.com/automate/nightwatch-integration
2. https://www.browserstack.com/automate/nightwatch

The problem is that these pages seem to contradict each other. The first page recommends this tool, but the second page does not. When I mentioned this to the BrowserStack support team, they were surprised that I had found the first page and essentially told me to ignore it.

What gives? 🤷‍♂️

**Comment by Varun-garg** [comment]
Sorry for the confusion @openjck . Guys, we have a dedicated repo for nightwatch that was just updated for latest nightwatch version. Please refer to it [here](https://github.com/browserstack/nightwatch-browserstack). This repo will be archived.

We are also removing the first the doc page.
